Repository OSGeo/gdal-grass, pull requests merged in 2024-02, with the labels that each got.

#39 packaging: generate release notes
  utils/generate_release_notes.py
  utils/git_author_github_name.csv
  utils/release.yml
Labels: packaging

#42 cmake: fix configure of Proj and PostgreSQL in standard locations
  CMakeLists.txt
  cmake/FindPROJ.cmake
  cmake/FindPostgreSQL.cmake
Labels: bug, packaging

#43 docs: add note that Autotools configure will be deprecated after the 1.0.3 release
  README.md
Labels: documentation
